version: "3.9"

services:
  backend:
    build: .
    container_name: velopress-backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
    restart: unless-stopped
